name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort
        
    - name: Check code formatting
      run: |
        black --check .
        isort --check-only .
        flake8 .
        
    - name: Run security checks
      run: |
        pip install bandit safety
        bandit -r .
        safety check
        
    - name: Check dependencies
      run: |
        pip check

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Run Tests
      run: |
        python -m pytest tests/
        
    - name: Check Coverage
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report --fail-under=80 